name: Issue triage

on:
  issues:
    types: [opened]

env:
  IN_MAINTAINER_LIST: ${{ contains(secrets.MAINTAINER_LIST, github.actor) }}

jobs:
  AddLabelsForIssueTriage:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Issue Triage Labels
        uses: github/issue-labeler@v3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler-issue-triage.yml
          enable-versioned-regex: 0
          include-title: 1
